import json
import logging
from typing import Dict, Any, List, Optional, Union, Callable
from magda_agent.skills.registry import SkillRegistry

logger = logging.getLogger(__name__)

class AgentSkillsImporter:
    """
    Importer for loading and registering external agentskills.io standard formats into Magda.
    Conforms to the open agentskills.io schema standard.
    """

    def __init__(self, registry: Optional[SkillRegistry] = None) -> None:
        """
        Initializes the AgentSkillsImporter with an optional SkillRegistry.

        Args:
            registry: Optional SkillRegistry instance to register imported skills into.
        """
        self.registry = registry

    def _create_dynamic_skill(self, skill_def: Dict[str, Any]) -> Callable[..., Any]:
        """
        Creates a dynamic skill function based on the agentskills.io definition.

        Args:
            skill_def: Dictionary representing the skill definition.

        Returns:
            A callable dynamic skill function.
        """
        name: str = skill_def.get("name", "unknown_skill")
        description: str = skill_def.get("description", "No description provided.")

        def dynamic_skill(**kwargs: Any) -> str:
            """Dynamic skill generated by AgentSkillsImporter."""
            logger.info(f"Executing imported skill: {name} with args: {kwargs}")
            return f"Executed imported skill '{name}' successfully with args: {kwargs}"

        dynamic_skill.__name__ = name
        dynamic_skill.__doc__ = description

        # Support both 'parameters' and 'inputSchema' under agentskills.io format
        if "parameters" in skill_def:
            setattr(dynamic_skill, "__mcp_schema__", skill_def["parameters"])
        elif "inputSchema" in skill_def:
            setattr(dynamic_skill, "__mcp_schema__", skill_def["inputSchema"])

        return dynamic_skill

    def validate_skill_definition(self, skill_def: Dict[str, Any]) -> bool:
        """
        Validates whether a skill definition conforms to the basic agentskills.io schema format.

        Args:
            skill_def: The skill definition dictionary to validate.

        Returns:
            True if valid, False otherwise.
        """
        if not isinstance(skill_def, dict):
            logger.warning("Skill definition must be a dictionary.")
            return False

        if "name" not in skill_def or not isinstance(skill_def["name"], str) or not skill_def["name"].strip():
            logger.warning("Skill definition is missing a valid 'name' field.")
            return False

        if "description" not in skill_def or not isinstance(skill_def["description"], str):
            logger.warning("Skill definition is missing a valid 'description' field.")
            return False

        return True

    def import_skills(self, data: Union[Dict[str, Any], List[Dict[str, Any]], str]) -> List[Callable[..., Any]]:
        """
        Parses the provided agentskills.io formatted data (which can be a JSON string,
        a dictionary of a single skill, a dictionary containing a 'skills' list,
        or a list of skill dictionaries) and generates dynamic skill functions.

        Args:
            data: Input data representing the skill(s).

        Returns:
            A list of callable dynamic skill functions successfully imported.
        """
        parsed_data: Any = None
        if isinstance(data, str):
            try:
                parsed_data = json.loads(data)
            except json.JSONDecodeError as e:
                logger.error(f"Failed to parse agentskills.io JSON input: {e}")
                return []
        else:
            parsed_data = data

        skills_list: List[Dict[str, Any]] = []

        if isinstance(parsed_data, list):
            skills_list = parsed_data
        elif isinstance(parsed_data, dict):
            if "skills" in parsed_data and isinstance(parsed_data["skills"], list):
                skills_list = parsed_data["skills"]
            else:
                skills_list = [parsed_data]
        else:
            logger.warning("Unsupported data format for agentskills.io import.")
            return []

        imported_funcs: List[Callable[..., Any]] = []

        for skill_def in skills_list:
            if self.validate_skill_definition(skill_def):
                func = self._create_dynamic_skill(skill_def)
                imported_funcs.append(func)
                # If a registry is configured, register the skill automatically
                if self.registry is not None:
                    name = skill_def["name"]
                    description = skill_def["description"]
                    self.registry.register_skill(name=name, func=func, description=description)
                    logger.info(f"Registered imported skill '{name}' into registry.")
            else:
                logger.warning(f"Skipping invalid skill definition: {skill_def}")

        return imported_funcs
