import json
import logging
from typing import Optional, Dict, Any

from magda_agent.llm_client import LLMClient


class CriticEvaluator:
    """
    Critic Evaluator Agent part of the Triad Architecture.
    Inspired by the Claude Agent Teams trend.
    This component rigorously evaluates a generator's output using an LLM to assign scores
    on usefulness, accuracy, completeness, and emotional adequacy.
    """

    def __init__(self, llm: LLMClient) -> None:
        """
        Initializes the CriticEvaluator with an LLM client.

        Args:
            llm (LLMClient): The LLM client to use for evaluations.
        """
        self.llm = llm
        self.last_evaluation: Optional[Dict[str, Any]] = None

    async def evaluate_generator_output(self, user_input: str, generator_output: str) -> Optional[Dict[str, Any]]:
        """
        Rigorously evaluates the generator output.

        Args:
            user_input (str): The original user input or prompt.
            generator_output (str): The generated response.

        Returns:
            Optional[Dict[str, Any]]: A dictionary containing the evaluation scores and feedback,
            or None if the evaluation fails.
        """
        prompt = (
            "You are a rigorous Critic Evaluator Agent.\n"
            "Evaluate the following output generated by another agent based on the user's input.\n"
            "Score the response from 1 to 10 on the following criteria:\n"
            "- usefulness\n"
            "- accuracy\n"
            "- completeness\n"
            "- emotional_adequacy\n\n"
            f"User input: {user_input}\n"
            f"Generator Output: {generator_output}\n\n"
            "Respond ONLY with a valid JSON object strictly matching this format:\n"
            "{\n"
            '  "usefulness": 8,\n'
            '  "accuracy": 9,\n'
            '  "completeness": 7,\n'
            '  "emotional_adequacy": 8,\n'
            '  "average_score": 8.0,\n'
            '  "feedback": "A concise explanation for the scores."\n'
            "}"
        )

        messages = [{"role": "system", "content": prompt}]
        max_retries = 3

        for attempt in range(max_retries):
            try:
                evaluation_text = await self.llm.chat_completion(messages, temperature=0.1)

                # Clean up potential markdown formatting wrapping the JSON
                if "```" in evaluation_text:
                    parts = evaluation_text.split("```")
                    if len(parts) >= 3:
                        evaluation_text = parts[1]
                        if evaluation_text.strip().startswith("json"):
                            evaluation_text = evaluation_text.strip()[4:]

                evaluation = json.loads(evaluation_text.strip())

                # Validate expected keys are present
                expected_keys = ["usefulness", "accuracy", "completeness", "emotional_adequacy", "average_score", "feedback"]
                if not all(key in evaluation for key in expected_keys):
                    raise ValueError(f"Missing expected keys in JSON output. Got: {list(evaluation.keys())}")

                self.last_evaluation = evaluation
                return evaluation

            except json.JSONDecodeError as e:
                logging.warning(f"JSON decoding error in CriticEvaluator attempt {attempt + 1}/{max_retries}: {e}. Retrying...")
                if attempt == max_retries - 1:
                    logging.error("Max retries reached for CriticEvaluator JSON parsing.")
                    return None
            except ValueError as e:
                logging.warning(f"Validation error in CriticEvaluator attempt {attempt + 1}/{max_retries}: {e}. Retrying...")
                if attempt == max_retries - 1:
                    logging.error(f"Max retries reached: {e}")
                    return None
            except Exception as e:
                logging.error(f"Unexpected error in CriticEvaluator: {e}")
                return None

        return None
