from typing import Dict, Any
import logging

from magda_agent.llm_client import LLMClient

class EvaluatorAgent:
    """
    Evaluator Agent Team Module.
    Inspired by Claude Agent SDK (Planner, Generator, Evaluator).
    Evaluates the Generator's outputs before finalizing.
    """
    def __init__(self, llm: LLMClient):
        self.llm = llm

    async def evaluate_output(self, generator_output: str, user_request: str) -> Dict[str, Any]:
        """
        Evaluates the output produced by the Generator Agent against the original user request.

        Args:
            generator_output (str): The text output generated.
            user_request (str): The initial user request or context.

        Returns:
            Dict[str, Any]: An evaluation result containing 'score', 'approved', and 'feedback'.
        """
        prompt = (
            "Evaluate the following output generated by an AI assistant in response to a user request.\n"
            "Assess it on correctness, relevance, and completeness.\n\n"
            f"User Request: {user_request}\n"
            f"Generated Output: {generator_output}\n\n"
            "Provide your evaluation as a JSON object with the following keys:\n"
            '- "score": an integer from 1 to 10.\n'
            '- "approved": a boolean indicating if the output is acceptable (score >= 7).\n'
            '- "feedback": a brief explanation for the evaluation.\n'
        )

        messages = [{"role": "system", "content": prompt}]
        try:
            response_text = await self.llm.chat_completion(messages, temperature=0.1)
            # Basic parsing logic (assuming LLM returns standard JSON or markdown-wrapped JSON)
            import json

            if "```" in response_text:
                response_text = response_text.split("```")[1]
                if response_text.startswith("json"):
                    response_text = response_text[4:]

            evaluation = json.loads(response_text.strip())
            return {
                "score": evaluation.get("score", 0),
                "approved": evaluation.get("approved", False),
                "feedback": evaluation.get("feedback", "No feedback parsed.")
            }
        except Exception as e:
            logging.error(f"Evaluator Agent failed to parse LLM response: {e}")
            return {"score": 0, "approved": False, "feedback": f"Evaluation error: {e}"}
