import pytest
from magda_agent.integration.a2a_auth import A2AAuthTokenDelegation

def test_a2a_auth_token_delegation_generate_token():
    """Test generating a new token."""
    auth_delegation = A2AAuthTokenDelegation()
    token = auth_delegation.generate_token()

    assert token.startswith("a2a_auth_")
    assert len(token) > len("a2a_auth_")
    assert token in auth_delegation._active_tokens

def test_a2a_auth_token_delegation_validate_token_success():
    """Test successful token validation."""
    auth_delegation = A2AAuthTokenDelegation()
    token = auth_delegation.generate_token()

    is_valid = auth_delegation.validate_token(token)
    assert is_valid is True

def test_a2a_auth_token_delegation_validate_token_failure():
    """Test failing token validation with an unauthorized delegate."""
    auth_delegation = A2AAuthTokenDelegation()

    # Trying to validate a token that wasn't generated by this manager
    is_valid = auth_delegation.validate_token("invalid_token")
    assert is_valid is False

def test_a2a_auth_token_delegation_revoke_token():
    """Test revoking a token."""
    auth_delegation = A2AAuthTokenDelegation()
    token = auth_delegation.generate_token()

    assert auth_delegation.validate_token(token) is True

    # Revoke the token
    revoked = auth_delegation.revoke_token(token)
    assert revoked is True

    # Now validation should fail
    assert auth_delegation.validate_token(token) is False

def test_a2a_auth_token_delegation_revoke_invalid_token():
    """Test revoking a token that does not exist."""
    auth_delegation = A2AAuthTokenDelegation()

    revoked = auth_delegation.revoke_token("invalid_token")
    assert revoked is False
