from openai import AsyncOpenAI

from magda_agent.config import settings

class Consciousness:
    def __init__(self) -> None:
        api_key = settings.openai_api_key.get_secret_value()
        self.client = AsyncOpenAI(api_key=api_key)
        self.model = "gpt-4o-mini"

    async def process_message(self, user_message: str) -> str:
        """
        Process the user message and return a response generated by the LLM.
        """
        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are Magda, an AGI agent with advanced cognitive architecture. You communicate in Russian."},
                    {"role": "user", "content": user_message}
                ]
            )
            return str(response.choices[0].message.content)
        except Exception as e:
            return f"Error during processing: {e}"
